### ISSUE TITLE
how can i pass multiple args

### ISSUE THREAD

**Issue by tbaror** [nmmapper/python3-nmap#18]
Hi,
I am trying to run multiple args but seems not gettings all args ,shown below 
`nmap.nmap_version_detection("192.168.1.10",args="-O -p- --script=freevulnsearch.nse")`

Please advice
Thanks

**Comment by wangoloj** [comment]
Then there is a bug there, the main bug could be that we don't parse the results of all arguments. We only parse and return `nmap_version_detection`, but not --script. We need to fix that.

**Comment by starnightcyber** [comment]
Same question!
I think you'd better define a kind of 'normal' function to accept args like scan() in python-nmap.
Using quit a few args is a very common when using nmap command.

```
import nmap
nm = nmap.PortScanner()
nm.scan(ip, '80, 445', '-v -n -sS -T4 -Pn')
```

**Comment by nmmapper** [comment]
That's a great Idea, you can open a pull request

**Comment by starnightcyber** [comment]
I need to figure out how you did in python-nmap first. 
It will take some time.
