### ISSUE TITLE
TypeError: scan_command() got an unexpected keyword argument 'arg'

### ISSUE THREAD

**Issue by Zian25** [nmmapper/python3-nmap#32]
When I try to call OS detection, I get the error below:

os_deteccao = nmap.nmap_os_detection(ip)
  File "C:\Python38\lib\site-packages\nmap3\nmap3.py", line 206, in nmap_os_detection
    xml_root = self.scan_command(target=target, arg=arg, args=args)
TypeError: scan_command() got an unexpected keyword argument 'arg'

**Comment by nmmapper** [comment]
Yes this is a bug thanks. We shall fix it.

**Comment by Zian25** [comment]
I'm using this:
`nmap = nmap3.NmapScanTechniques()`
`os_deteccao = nmap.nmap_os_detection(ip)`,

when I call so:
`nmap = nmap3.Nmap()`, 
i get "AttributeError: 'Nmap' object has no attribute 'nmap_syn_scan'",

and: "nmap = Nmap()
NameError: name 'Nmap' is not defined"

**Comment by nmmapper** [comment]
Yeah that's right.  I have a look at this documentation.

https://github.com/nmmapper/python3-nmap#nmap-scanning-techniques

There are 3 classes so far
```
   import nmap3

    nmap3.Nmap()

    nmap3.NmapHostDiscovery()

    nmap3.NmapScanTechniques()
```
