### ISSUE TITLE
Port Scan

### ISSUE THREAD

**Issue by DeityLink2018** [nmmapper/python3-nmap#33]
Is there a way that you can scan all 65535 ports using python3-nmap or am I just missing the right function to do so?

**Comment by nmmapper** [comment]
It's possible

```
 import nmap3
 nmap = nmap3.Nmap()
 results = nmap.scan_top_ports("host", args="-p 65535")
```

**Comment by DeityLink2018** [comment]
Gotcha, thank you!

**Comment by DeityLink2018** [comment]
So, the args="-p 65535" doesn't work. When ever i start a nc listener on a RHP my script is not picking anything up. It still only searches for the top common ports

**Comment by DeityLink2018** [comment]
I think I know the problem. You are using --top-ports for the nmap command. When running a normal nmap command, --top-ports only reads the first "#" in this case its the default variable of 10. If i test this I get the same results as my script. If I change that default value in my command to 65535, it picks everything up. I don't know a good change for this personally but this information may help.

**Comment by S4eedb** [comment]
`import nmap3

 nmap = nmap3.Nmap()

 results = nmap.scan_top_ports("host", default="65535")`

**Comment by nmmapper** [comment]
Try the the solution from @S4eedb if that does not work(probably it should) then try below.

```
  import nmap3
  nmap = nmap3.NmapScanTechniques()
  result = nmap.nmap_tcp_scan("192.168.178.1", args="-p 65535")
```

Might need to add a function for scan_all_ports(default="65535"). Because the script defines each nmap command sometimes nmap args as function simple functions.

**Comment by DeityLink2018** [comment]
Ill give the solution a try, Ive been playing around with the code this morning and and I keep running into the problem that --top-port wont pick up anything beyond 65000 for some reason the moment I set nc to 65001, it wont pick it up anymore
