### ISSUE TITLE
Nmap -sV -T3

### ISSUE THREAD

**Issue by DeLuca92** [nmmapper/python3-nmap#39]
Hello,
How I do nmap  -sV -T3 ip in this api?

Thx

**Comment by nmmapper** [comment]
Hello you try the following
```
import nmap3
nmap = nmap3.Nmap()
version_result = nmap.nmap_version_detection("your-host.com", args="-T3")
```

Let us know if it works. If you don't get the results you want you can get the raw output(xml) and parse it yourself

`nmap.raw_ouput`

**Comment by DeLuca92** [comment]
I Will try this :).
It's possible get cve?

**Comment by nmmapper** [comment]
Not sure,  requires testing

**Comment by f-froehlich** [comment]
You can use https://github.com/f-froehlich/nmap-scan its compatible to the nmap DTD an you can get the CVE

**Comment by nmmapper** [comment]
As for CVE that might be an interesting future project. I Hope the `-T3` worked for you otherwise we are going to close this issue!
