### ISSUE TITLE
Multi-thread

### ISSUE THREAD

**Issue by guanana** [nmmapper/python3-nmap#44]
Hello here,

I'm using your library and I was hopping I could use multithreading to speed up parallel scans.
I already have a list of hosts that are up and I'm passing them into the scan as:

```
nmap = nmap3.Nmap()
for host in my_list:
  nmap.nmap_version_detection(target=host)
```
I've been trying to add some parallelism with async or Parallel from joblib without success

**Comment by f-froehlich** [comment]
You may want to use https://github.com/f-froehlich/nmap-scan it' support multi threading and also the full nmap DTD

**Comment by nmmapper** [comment]
We might think of adding multi-threading. Though we wanted this script to be as easy as possible and straight to the point. Unlike similiar tools(like quoted above) which are a little bit not easy. On the other hand you can build you own multi-threading here is how you might do it.

```
import threading
import logging
logging.basicConfig(level=logging.DEBUG,format='Nmap (%(threadName)-10s) %(message)s',)

class Nmap3Threads(threading.Thread):
    def __init__(self, nmap, host):
         threading.Thread.__init__(self)
         self.nmap = nmap
         self.host = host
         
    def run(self):
        logging.debug('Performing scan')
        self.nmap.nmap_version_detection(target=self.host)

if __name__=="__main__":
     nmap = nmap3.Nmap()
     my_list = []
     for host in my_list:
        t = Nmap3Threads(nmap, host)
        t.start()
```

We might try to see how we might incorporate multi-threading.
Thank you
