### ISSUE TITLE
json output for 'macaddress': None breaks json beautification. 

### ISSUE THREAD

**Issue by jrknox1977** [nmmapper/python3-nmap#45]
json output for 'macaddress': None breaks json beautification. 
Error I recieved:

Parse error on line 1:
...: [], "macaddress": None, "state": {"sta
-----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

**Comment by f-froehlich** [comment]
Well json don't have the None type it's using null instead. You might want to use https://github.com/f-froehlich/nmap-scan the current master branch (not the version 1.0.0) supports pretty json formatting and also you can import your json again.

**Comment by nmmapper** [comment]
Try to update your python3-nmap installation using the git-repo, that issue was fixed with this pull request https://github.com/nmmapper/python3-nmap/pull/42 and it's not yet in pip.

pip install --upgrade git@github.com:nmmapper/python3-nmap.git

**Comment by RafhaanShah** [comment]
When will this be released on pip?

**Comment by nmmapper** [comment]
Am going to do that this week.
