### ISSUE TITLE
nmap_version_detection with specific port number

### ISSUE THREAD

**Issue by hash3liZer** [nmmapper/python3-nmap#46]
How do I run the `nmap_version_detection` for a specific port? In my case, it's 80 and I am only willing to get a server banner. The documentation has the following header: 

```
nmap_version_detection(self, target, arg='-sV', args=None)
```

However, I am not able to test it for a specific port.

**Comment by Danyboy** [comment]
As I understand it, the port can be passed as an argument
`results = nmap.scan_top_ports("host", args="-p 80")`
[python3-nmap/issues/33](https://github.com/nmmapper/python3-nmap/issues/33)

**Comment by hash3liZer** [comment]
Thanks, this seems to work. I did the following: 

```
nmap_version_detection(target, args="-p 80")
```
