### ISSUE TITLE
I think a optional timeout argument will be helpful.

### ISSUE THREAD

**Issue by valleygtc** [nmmapper/python3-nmap#48]

**Comment by valleygtc** [comment]
like this:
```python
nmap = nmap3.Nmap()
result = nmap.nmap_version_detection('your-host.com', timeout=600)
```

I think we just pass this argument into `sub_proc.communicate(timeout=timeout)` func is enough.

**Comment by nmmapper** [comment]
That's a good suggestion! You can create a pull request with that feature. If you do that ensure that it's not required, as some nmap commands take longer to finish, like subnet scans combined with other detections.
