### ISSUE TITLE
nmap_os_detection not working on Windows 10 20H2

### ISSUE THREAD

**Issue by MrEnergy64** [nmmapper/python3-nmap#52]
Dear nmap3 creator,

first of all I have to say thank you for your python3 nmap3 module. I've created a little nmap frontend with this nmap3 module:
https://github.com/MrEnergy64/IPventur-Python-Curses

when I start my program under Linux, most scan technics are working fine, when I did it under Window 10 with scan-technic:
nmap_os_detection, I get this error:

Traceback (most recent call last):
  File "C:\Users\mrene\Documents\Python\IPventur-Python-1.0v3.py", line 222, in <module>
    results = nmap.nmap_os_detection(f'{ip}')
  File "C:\Users\mrene\AppData\Local\Programs\Python\Python39\lib\site-packages\nmap3\utils.py", line 74, in wrapper
    if(os.geteuid() == 0):
AttributeError: module 'os' has no attribute 'geteuid'

I know that geteuid is not exist on Windows 10, therefore I used a little trick to identify if someone startet the program in an administrator window or not:

if os_version == "Windows":
    import win32api
    check = win32api.GetConsoleTitle()
    if "Administrator" in check:
        User = "Administrator"
    else:
        User = "Normal User"

so, maybe this could be a solution for you as well. Or is my issue complete different?

Thanks,

Norman

**Comment by nmmapper** [comment]
I will look into it. If you can make a pull request that would be quick. Thank you

**Comment by MrEnergy64** [comment]
Brilliant, thanks.

 

Von: Nmmapper ***@***.***> 
Gesendet: Sonntag, 30. Mai 2021 14:49
An: nmmapper/python3-nmap ***@***.***>
Cc: MrEnergy64 ***@***.***>; Author ***@***.***>
Betreff: Re: [nmmapper/python3-nmap] nmap_os_detection not working on Windows 10 20H2 (#52)

 

Closed #52 <https://github.com/nmmapper/python3-nmap/issues/52>  via  <https://github.com/nmmapper/python3-nmap/commit/3d558449bc76017a03dac2fc0dc2c1e7cf9a38a9> 3d55844.
