### ISSUE TITLE
bug - KeyError: 'enable_ipv6' when running NmapHostDiscovery().nmap_portscan_only(target='127.0.0.1')

### ISSUE THREAD

**Issue by jomonson** [nmmapper/python3-nmap#75]
I suspect this bug was introduced when the support for IPv6 was added. The code expects enable_ipv6 argument to be given but it's not given a default value if no argument is supplied. See the following snippet:
```
if self.enable_ipv6:
    return self.default_args.format(nmap=self.nmaptool, outarg="-oX", enable_ipv6="-6")
else:
    return self.default_args.format(nmap=self.nmaptool, outarg="-oX")
```

**Comment by nmmapper** [comment]
You can open a pull request. Thanks

**Comment by nmmapper** [comment]
This issue you just have to do this

```
nmap = NmapHostDiscovery()
result = nmap.nmap_portscan_only(target='127.0.0.1', args="-6")
```
It will work as expected
