### ISSUE TITLE
callback_progress

### ISSUE THREAD

**Issue by majidmc2** [nmmapper/python3-nmap#81]
Hi
I have a feature in mind. It is to have a **"callback_progress"** that displays its progress whenever a function is executed.

EX:

```
>>> def print_status(i):
           print(str(i))

>>> import nmap3
>>> nmap = nmap3.Nmap()
>>> nmap.nmap_version_detection("your-host.com", callback_progress=print_status)
```

```
10%
30%
90%
100%
[...]
```

**Comment by yichen115** [comment]
I really need this function🤩

**Comment by nmmapper** [comment]
Feel free to work on it and I will merge it, it appears you can work on it.
