### ISSUE TITLE
Can't tell when a request timed out

### ISSUE THREAD

**Issue by jpseara** [nmmapper/python3-nmap#83]
Hello!

First of all thank you for this fantastic tool.

I have noted that it is nearly impossible to detect a timeout in your libraries. I even tried to add -v and there's nothing in the output.

Here's my call:

`nmap_version_detection(target_ip, args="-Pn --script vulners -p80 --host-timeout 5 -v")`

There's nothing in the output that allows me to know if it timed out. Even when I know it did time out, it will just output whatever info it grabbed till then, and the summary says we are good:

```
'summary': 'Nmap done at Tue Oct 11 01:33:53 2022; 1 IP address '
                        '(1 host up) scanned in 23.91 seconds',
```

If I run the same command in BASH, I can grep for "timed out" if I use -v:

```
$ sudo /usr/bin/nmap -oX - -O -sV -Pn --host-timeout 5 192.168.122.51 -p80 --script vulners -v | grep timed

<taskend task="Service scan" time="1665448215" extrainfo="1 host timed out"/>
```

It seems like you are not parsing this in your libraries.

Is there any way for me to know if a timeout happened when using your library?

This is really important in order to understand if the command actually worked or not.

**Comment by nmmapper** [comment]
That's a good point. Feel free to open a pull request that adds the feature you want.

**Comment by jpseara** [comment]
@nmmapper PR created [1].

[1] https://github.com/nmmapper/python3-nmap/pull/84
