### ISSUE TITLE
Unable to parse xml output

### ISSUE THREAD

**Issue by javelineou** [nmmapper/python3-nmap#90]
Hello,
I'm trying to run this code on Python 3.11,
```
import nmap3
nmap = nmap3.Nmap()
nmap.nmap_version_detection("127.0.0.1", args="--script vulners -oX scan_result.xml")
```
Everytime it runs, it did give me an .xml file but this error is shown in the terminal making the program stop (showstopping),
```
Traceback (most recent call last):
  File "d:\vm\vm\project\test.py", line 5, in <module>
    nmap.nmap_version_detection(
  File "C:\Users\Jave\AppData\Local\Programs\Python\Python311\Lib\site-packages\nmap3\nmap3.py", line 196, in nmap_version_detection
    xml_root = self.scan_command(target=target, arg=arg, args=args, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jave\AppData\Local\Programs\Python\Python311\Lib\site-packages\nmap3\nmap3.py", line 127, in scan_command
    xml_root = self.get_xml_et(output)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jave\AppData\Local\Programs\Python\Python311\Lib\site-packages\nmap3\nmap3.py", line 280, in get_xml_et
    raise NmapXMLParserError()
nmap3.exceptions.NmapXMLParserError: Unable to parse xml output
```

I don't really understand what's the error here, but I somehow believe this is about the lxml package problem. Thanks for helping.

**Comment by javelineou** [comment]
![image](https://github.com/nmmapper/python3-nmap/assets/63649797/51997eb6-7d0b-49bb-808a-f0b03d05d623)
Also, just found something. When I hover the nmap.nmap_version_detection method, the description say it performs dns-brute script (?)

**Comment by javelineou** [comment]
@nmmapper please help :')

**Comment by javelineou** [comment]
@f-froehlich please help. thanks

**Comment by nmmapper** [comment]
Do You have nmap installed on your PC?

**Comment by javelineou** [comment]
Yes I do.
```
Nmap version 7.94 ( https://nmap.org )
Platform: i686-pc-windows-windows
```

**Comment by nmmapper** [comment]
Then I will test it out and let you know

**Comment by priyambajpai22** [comment]
@javelineou  what is the expected behaviour?

**Comment by javelineou** [comment]
> @javelineou what is the expected behaviour?

It should generate ```scan_result.xml``` and make no error

**Comment by priyambajpai22** [comment]
@javelineou hi , i have generated pr for this issue, #95 
-https://github.com/nmmapper/python3-nmap/pull/95
