### ISSUE TITLE
Inconsistent Port Status Results with Python Nmap

### ISSUE THREAD

**Issue by alperensayar** [nmmapper/python3-nmap#94]
I've encountered an issue while performing port scanning with Python Nmap on external IP addresses. The issue is inconsistent port status results.

For instance, when performing a scan on Google's IP addresses or any other external IP, the first few scans show all ports as open. However, upon subsequent scans, the results become more accurate and reflect the true open, closed, and filtered port status.

Its my script:
import nmap

def scan_ports(target):
    nm = nmap.PortScanner()
    nm.scan(target, arguments='-p 1-65535 -T5') # scanning all ports with timing template T5
    open_ports = []
    for host in nm.all_hosts():
        for proto in nm[host].all_protocols():
            lport = nm[host][proto].keys()
            for port in lport:
                if nm[host][proto][port]['state'] == 'open':
                    service_name = nm[host][proto][port]['name']
                    print(f"Port {port}/{proto} is open. Service: {service_name}")

if __name__ == "__main__":
    target_ip = "<target-ip>"  # Replace with the target IP address
    scan_ports(target_ip)

I am currently using the -T5 timing template. However, the initial results of the scan indicate all ports are open, which is inconsistent with subsequent scans and other port scanning tools.

This behaviour makes it challenging to accurately determine the state of ports during the initial stages of the scan.

Any help or guidance to fix this issue would be greatly appreciated.

**Comment by nmmapper** [comment]
Seems you are using a different module which is not `nmap3`. So we can't help you with that.
