### ISSUE TITLE
ModuleNotFoundError: No module named 'nmapparser', 'nmap3', 'nmap'

### ISSUE THREAD

**Issue by danindiana** [nmmapper/python3-nmap#99]
re: https://github.com/nmmapper/python3-nmap/issues/79

**System Information:**

* **OS:** 

 OS: Ubuntu 22.04 jammy
 Kernel: x86_64 Linux 6.5.0-25-generic
 Uptime: 3h 17m
 Packages: 3597
 Shell: bash 5.1.16

* **Python Version:** [Output of `python --version` or `python3 --version`]
python3 --version
Python 3.10.12

**Steps Taken:**

1. **Checked existing packages:**

   ```bash
   pip list
   Package  Version
   ---------- -------
   pip    22.0.2
   setuptools 59.6.0
   simplejson 3.19.2
Attempted to install 'python3-nmap':

Bash
(env) user@hostname:~/some/path$ pip install python3-nmap
Collecting python3-nmap
 Using cached python3_nmap-1.6.0-py3-none-any.whl (26 kB)
# ... (Rest of the installation output) ... 
Executed my script:

Bash
(env) user@hostname:~/some/path$ sudo python3 my_script.py
Traceback (most recent call last):
 File "/home/user/some/path/my_script.py", line 1, in <module>
  import nmap 
ModuleNotFoundError: No module named 'nmap'
Tried various module names and installation attempts:

sudo python3 my_script.py (Tried without sudo)
pip install nmapparser
pip install nmap3 (Tried uninstalling and re-installing)
pip install python-nmap

**Comment by nmmapper** [comment]
It's supposed to be `import nmap3` not `import nmap`

**Comment by danindiana** [comment]
> It's supposed to be `import nmap3` not `import nmap`

I know. I tried that. Still no dice.

**Comment by danindiana** [comment]
> It's supposed to be `import nmap3` not `import nmap`

Here is the code I was trying to run:

import nmap3
import sys

def trace_and_extract(target):
    print(f"Executing traceroute for target: {target}", file=sys.stderr)
    sys.stderr.flush()

    nm = nmap.PortScanner()
    nm.scan(target, arguments='--traceroute')

    if target in nm.all_hosts():
        trace_info = nm[target]['trace']
        print(f"Traceroute results for {target}:", file=sys.stderr)
        for hop in trace_info['hops']:
            print(f"Hop {hop['ttl']}: {hop['ipaddr']}", file=sys.stderr)
            sys.stderr.flush()
        return [hop['ipaddr'] for hop in trace_info['hops'] if 'ipaddr' in hop]
    else:
        print(f"No traceroute information found for {target}", file=sys.stderr)
        sys.stderr.flush()
        return []

def recursive_trace(current_url, depth):
    if not (current_url.startswith("http://") or current_url.startswith("https://")):
        current_url = "www." + current_url

    print(f"Entering recursive_trace with URL: {current_url}, depth: {depth}", file=sys.stderr)
    sys.stderr.flush()

    if depth == 0:
        print("Maximum depth reached. Exiting recursion.", file=sys.stderr)
        sys.stderr.flush()
        return

    discovered_ips = trace_and_extract(current_url)
    for ip in discovered_ips:
        print(f"Recursing with IP: {ip}, depth: {depth - 1}", file=sys.stderr)
        sys.stderr.flush()
        recursive_trace(ip, depth - 1)

if __name__ == "__main__":
    target_url = input("Enter the target URL or IP address: ")
    try:
        recursion_depth = int(input("Enter the recursion depth (number of levels): "))
    except ValueError:
        print("Recursion depth must be an integer.", file=sys.stderr)
        sys.exit(1)

    print(f"Starting recursive traceroute for target: {target_url}, depth: {recursion_depth}", file=sys.stderr)
    sys.stderr.flush()

    recursive_trace(target_url, recursion_depth)

**Comment by nmmapper** [comment]
You are using a wrong module inside nmap3, follow the documentation here https://github.com/nmmapper/python3-nmap nmap3 does not have module `PortScanner`
